// 存取 key 值方便直接關聯調用
export const ImagePack = {
    qz28g_btn_nograb: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_nograb.png'),
    qz28g_btn_multi: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi.png'),
    qz28g_btn_multi_number_0: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_0.png'), // 暫時這樣寫，後面再改合圖
    qz28g_btn_multi_number_1: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_1.png'),
    qz28g_btn_multi_number_2: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_2.png'),
    qz28g_btn_multi_number_3: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_3.png'),
    qz28g_btn_multi_number_4: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_4.png'),
    qz28g_btn_multi_number_5: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_5.png'),
    qz28g_btn_multi_number_6: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_6.png'),
    qz28g_btn_multi_number_7: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_7.png'),
    qz28g_btn_multi_number_8: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_8.png'),
    qz28g_btn_multi_number_9: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_number_9.png'),
    qz28g_btn_multi_ba: require('../../res/gui/textures/qz28g/cn/i/qz28g_game_img/qz28g_btn_header/qz28g_btn_multi_ba.png'),
    qz_bet_number_0: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_0.png'),
    qz_bet_number_1: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_1.png'),
    qz_bet_number_2: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_2.png'),
    qz_bet_number_3: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_3.png'),
    qz_bet_number_4: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_4.png'),
    qz_bet_number_5: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_5.png'),
    qz_bet_number_6: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_6.png'),
    qz_bet_number_7: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_7.png'),
    qz_bet_number_8: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_8.png'),
    qz_bet_number_9: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_9.png'),
    qz_bet_number_x: require('../../res/gui/textures/common/qzgame_number/qz_bet_number_x.png'),
    qz_grab_number_0: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_0.png'),
    qz_grab_number_1: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_1.png'),
    qz_grab_number_2: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_2.png'),
    qz_grab_number_3: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_3.png'),
    qz_grab_number_4: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_4.png'),
    qz_grab_number_5: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_5.png'),
    qz_grab_number_6: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_6.png'),
    qz_grab_number_7: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_7.png'),
    qz_grab_number_8: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_8.png'),
    qz_grab_number_9: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_9.png'),
    qz_grab_number_x: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_x.png'),
    qz_grab_number_r: require('../../res/gui/textures/common/qzgame_number/qz_grab_number_r.png'),
    qz_grab_0: require('../../res/gui/textures/common/qzgame_ui/qz_grab_0.png'),
    qz_banker_icon: require('../../res/gui/textures/common/qzgame_ui/qz_banker_icon.png'),
    qz_box_light1: require('../../res/gui/textures/common/qzgame_ui/qz_box_light1.png'),
    qz_box_light2: require('../../res/gui/textures/common/qzgame_ui/qz_box_light2.png'),
    qz_choice_box: require('../../res/gui/textures/common/qzgame_ui/qz_choice_box.png'),

    icon_0: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_1: require('../../res/gui/textures/common/common_pic/icon_1.png'),
    icon_2: require('../../res/gui/textures/common/common_pic/icon_2.png'),
    icon_3: require('../../res/gui/textures/common/common_pic/icon_3.png'),
    icon_4: require('../../res/gui/textures/common/common_pic/icon_4.png'),
    icon_5: require('../../res/gui/textures/common/common_pic/icon_5.png'),
    icon_6: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_7: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_8: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_9: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_10: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    icon_11: require('../../res/gui/textures/common/common_pic/icon_0.png'),
    frame_0: require('../../res/gui/textures/common/common_pic/frame_0.png'),
    frame_1: require('../../res/gui/textures/common/common_pic/frame_1.png'),
    frame_2: require('../../res/gui/textures/common/common_pic/frame_2.png'),
    frame_3: require('../../res/gui/textures/common/common_pic/frame_3.png'),
    frame_4: require('../../res/gui/textures/common/common_pic/frame_4.png'),
    frame_5: require('../../res/gui/textures/common/common_pic/frame_5.png'),
    frame_6: require('../../res/gui/textures/common/common_pic/frame_6.png'),
    frame_7: require('../../res/gui/textures/common/common_pic/frame_7.png'),
    frame_8: require('../../res/gui/textures/common/common_pic/frame_8.png'),
    frame_9: require('../../res/gui/textures/common/common_pic/frame_9.png'),
    frame_10: require('../../res/gui/textures/common/common_pic/frame_10.png'),
    frame_11: require('../../res/gui/textures/common/common_pic/frame_11.png'),
    seat_gold_bar: require('../../res/gui/textures/common/common_pic/seat_gold_bar.png'),
    seat_play_bg: require('../../res/gui/textures/common/common_pic/seat_play_bg.png'),
    seat_player_bg: require('../../res/gui/textures/common/common_pic/seat_player_bg.png'),
    seat_location: require('../../res/gui/textures/common/common_pic/seat_location.png'),

    embossed_basecolor: require('../../res/textures/embossed/embossed_basecolor.jpg'),
    embossed_normal: require('../../res/textures/embossed/embossed_normal.jpg'),
    embossed_normal_height: require('../../res/textures/embossed/embossed_normal_height.jpg'),
    embossed_metallic: require('../../res/textures/embossed/embossed_metallic.jpg'),
    embossed_roughness: require('../../res/textures/embossed/embossed_roughness.jpg'),

    carpet_fleurdelis: require('../../res/textures/carpet/fleurdelis.jpg'),
    carpet_normal: require('../../res/textures/carpet/carpet_normal.png'),
    carpet_normal_height: require('../../res/textures/carpet/carpet_normal_height.png'),
    carpet_roughness: require('../../res/textures/carpet/carpet_roughness.png'),
    carpet_height: require('../../res/textures/carpet/carpet_height.png'),
};

export const ModelPack = {
    // 在這裡定義模型的 key 值
    dice: { url: require('../../res/models/dice.glb'), config: { isNeedRename: true } },
    dominoes: { url: require('../../res/models/dominoes.glb'), config: { isMultiMesh: true } },
    mahjong: { url: require('../../res/models/mahjong.glb'), config: { isMultiMesh: true } },
    angelwomon: { url: require('../../res/models/angelwomon.glb'), config: { isNeedRename: true, isMultiMesh: true, isAllInOne: true } },
    canterella: {
        url: require('../../res/models/canterella.glb'),
        config: { isNeedRename: true, isMultiMesh: true, isAllInOne: true },
    },
    canterella_dance: {
        url: require('../../res/models/canterella_dance.glb'),
        config: { isNeedRename: true, isMultiMesh: true, isAllInOne: true },
    },
    iuno_dance: {
        url: require('../../res/models/iuno_dance.glb'),
        config: { isNeedRename: true, isMultiMesh: true, isAllInOne: true },
    },
    iuno: {
        url: require('../../res/models/iuno.glb'),
        config: { isNeedRename: true, isMultiMesh: true, isAllInOne: true },
    },
};

export const ResourcesKey = {
    dice: 'dice',
    dominoes: 'dominoes',
    mahjong: 'mahjong',
    angelwomon: 'angelwomon',
    canterella: 'canterella',
    canterella_dance: 'canterella_dance',
    iuno_dance: 'iuno_dance',
    iuno: 'iuno',
};
